serverAddr = "ecs.zhelearn.com"
serverPort = 12803
auth.token = "vb*4#ZBm9NyGkKw%ofyQhrkiTsBc@@&7f7H9*e$tR37qyU9XQR&Tia3dH^eVaBe4B*!*pJwB#ZD4xNcm%6sgoYL$5$7d2m%xAkTVZTCwMF5lS3lNCoy$B!@EzGvkUvvn"

[[proxies]]
name = "webhook"
type = "http"
localIP = "127.0.0.1"
localPort = 5000
customDomains = ["github.zhelearn.com"]
